services:

  app:
    image: nyitcomatg/omm-se:latest
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omm-ace.entrypoints=http"
      - "traefik.http.routers.omm-ace.rule=Host(`comapp.nyit.edu`) && PathPrefix(`/omm_ace`)"
      - "traefik.http.middlewares.omm-ace-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.omm-ace.middlewares=omm-ace-https-redirect"
      - "traefik.http.routers.omm-ace-secure.entrypoints=https"
      - "traefik.http.routers.omm-ace-secure.rule=Host(`comapp.nyit.edu`) && PathPrefix(`/omm_ace`)"
      - "traefik.http.routers.omm-ace-secure.tls=true"
      - "traefik.http.routers.omm-ace-secure.middlewares=omm-ace-stripprefix"
      - "traefik.http.middlewares.omm-ace-stripprefix.stripprefix.prefixes=/omm_ace,/omm_ace/"
      - "traefik.http.services.omm-ace.loadbalancer.server.port=8080"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
